### ISSUE TITLE
Issue with DNS Resolution in namecheap-ddns

### ISSUE THREAD

**Issue by Pamalosebi** [nickjer/namecheap-ddns#5]
Hey,

I recently encountered an issue while using namecheap-ddns. The cryptic error message was as follows:
```
systemd[1]: Started ddns-update.service.
namecheap-ddns[PID]: Error: Failed to update example.org
namecheap-ddns[PID]: Caused by:
namecheap-ddns[PID]:     0: received fatal alert: InternalError
namecheap-ddns[PID]:     1: received fatal alert: InternalError
systemd[1]: ddns-update.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: ddns-update.service: Failed with result 'exit-code'.
```

I found that the domain `dynamicdns.park-your-domain.com.cdn.cloudflare.net` was blocked, which prevented it from being resolved over DNS. That website returns ones IP, I guess that is the logic this software uses...

I believe this is an detail that could be documented somewhere to help others who might encounter the same issue.

**Comment by nickjer** [comment]
Good to know. I am curious why `minreq` doesn't give a more helpful error with something like "could not resolve host". For now I'll try to add more context to the error this weekend when I have more time.

**Comment by nickjer** [comment]
This CLI does not perform a separate ip check. As you pointed out we do hit `dynamicdns.park-your-domain.com` because that is the location of their API to update your host.

If you do not supply an ip address at all then their API will automatically determine it from the ip address you used when hitting their endpoint. If you do supply an ip address then they just use that instead. In both cases we hit the same endpoint.

By the way, I am trying to replicate your behavior. I opened up the code and put in a nonsensical domain but I get a helpful error message...

```
Error: Failed to update host.domain.com

Caused by:
    0: failed to lookup address information: Name or service not known
    1: failed to lookup address information: Name or service not known
```

How are you blocking their API endpoint? Maybe I can try replicating it that way instead.

**Comment by nickjer** [comment]
Ok, I pushed up a new version that adds further context around the url that is problematic. This won't resolve the underlying nameserver issue but can help the user debug it faster.
